[project]
authors = ["Barry <baichuns@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "extract spatial lineament"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.*"
dask = ">=2024.8.0,<2025"
scipy = ">=1.13.1,<2"
rasterio = ">=1.4.1,<2"
scikit-image = ">=0.24.0,<0.25"
shapely = ">=2.0.6,<3"
rdp = ">=0.8,<0.9"
scikit-learn = ">=1.5.2,<2"
matplotlib = ">=3.9.2,<4"
geopandas = ">=1.0.1,<2"
xarray = ">=2024.7.0,<2025"
rioxarray = ">=0.15.0,<0.16"
colorcet = ">=3.1.0,<4"
ipywidgets = ">=8.1.5,<9"
ipykernel = ">=6.29.5,<7"
pyfftw = ">=0.14.0,<0.15"
